export const Resources = [
    ["bossBig",  '././images/pukes/bossBig.jpg']         ,
    ["bossSmall", '././images/pukes/bossSmall.jpg']      ,
    ["fe", "././images/pukes/fe.jpg"     ]               ,
    ["fg", "././images/pukes/fg.jpg"     ]               ,
    ["f3", "././images/pukes/f3.jpg"     ]               ,
    ["f4", "././images/pukes/f4.jpg"     ]               ,
    ["f5", "././images/pukes/f5.jpg"     ]               ,
    ["f6", "././images/pukes/f6.jpg"     ]               ,
    ["f7", "././images/pukes/f7.jpg"     ]               ,
    ["f8", "././images/pukes/f8.jpg"     ]               ,
    ["f9", "././images/pukes/f9.jpg"     ]               ,
    ["fa", "././images/pukes/fa.jpg"     ]               ,
    ["fb", "././images/pukes/fb.jpg"     ]               ,
    ["fc", "././images/pukes/fc.jpg"     ]               ,
    ["fd", "././images/pukes/fd.jpg"     ]               ,
    ["he", "././images/pukes/he.jpg"     ]               ,
    ["hg", "././images/pukes/hg.jpg"     ]               ,
    ["h3", "././images/pukes/h3.jpg"     ]               ,
    ["h4", "././images/pukes/h4.jpg"     ]               ,
    ["h5", "././images/pukes/h5.jpg"     ]               ,
    ["h6", "././images/pukes/h6.jpg"     ]               ,
    ["h7", "././images/pukes/h7.jpg"     ]               ,
    ["h8", "././images/pukes/h8.jpg"     ]               ,
    ["h9", "././images/pukes/h9.jpg"     ]               ,
    ["ha", "././images/pukes/ha.jpg"     ]               ,
    ["hb", "././images/pukes/hb.jpg"     ]               ,
    ["hc", "././images/pukes/hc.jpg"     ]               ,
    ["hd", "././images/pukes/hd.jpg"     ]               ,
    ["me", "././images/pukes/me.jpg"     ]               ,
    ["mg", "././images/pukes/mg.jpg"     ]               ,
    ["m3", "././images/pukes/m3.jpg"     ]               ,
    ["m4", "././images/pukes/m4.jpg"     ]               ,
    ["m5", "././images/pukes/m5.jpg"     ]               ,
    ["m6", "././images/pukes/m6.jpg"     ]               ,
    ["m7", "././images/pukes/m7.jpg"     ]               ,
    ["m8", "././images/pukes/m8.jpg"     ]               ,
    ["m9", "././images/pukes/m9.jpg"     ]               ,
    ["ma", "././images/pukes/ma.jpg"     ]               ,
    ["mb", "././images/pukes/mb.jpg"     ]               ,
    ["mc", "././images/pukes/mc.jpg"     ]               ,
    ["md", "././images/pukes/md.jpg"     ]               ,
    ["re", "././images/pukes/re.jpg"     ]               ,
    ["rg", "././images/pukes/rg.jpg"     ]               ,
    ["r3", "././images/pukes/r3.jpg"     ]               ,
    ["r4", "././images/pukes/r4.jpg"     ]               ,
    ["r5", "././images/pukes/r5.jpg"     ]               ,
    ["r6", "././images/pukes/r6.jpg"     ]               ,
    ["r7", "././images/pukes/r7.jpg"     ]               ,
    ["r8", "././images/pukes/r8.jpg"     ]               ,
    ["r9", "././images/pukes/r9.jpg"     ]               ,
    ["ra", "././images/pukes/ra.jpg"     ]               ,
    ["rb", "././images/pukes/rb.jpg"     ]               ,
    ["rc", "././images/pukes/rc.jpg"     ]               ,
    ["rd", "././images/pukes/rd.jpg"     ]               ,
    ["putPuke", '././images/putPuke.png'],
    ["cancel", '././images/cancel.png']
];

